---
definitions:
  adhoc:
    topics:
      - name:
          - "abhishek.walia.test.1"
          - "abhishek.walia.test.2"
          # - "_confluent-license"
        clients:
          # consumers:
          #   - id: "User:1111"
          #     group: "hello"
          producers:
            - id: "User:1121"
            - id: "User:1122"
              group: "hello"
            - id: "User:1123"
              group: "hello"
              enableIdempotence: true
            - id: "User:1124"
              group: "hello"
              enableIdempotence: true
              enableTransactions: true
          # connectors:
          #   - id: "User:1131"
          #     type: "source"
          #     clusterName: "connect-cluster"
          #   - id: "User:1132"
          #     type: "sink"
          #     clusterName: "connect-cluster"
          #   - id: "User:1133"
          #     type: "sink"
          #     clusterName: "connect-cluster"
          # ksql:
          #   - id: "User:1141"
          #     type: "read"
          #     clusterName: "ksql-cluster"
          #   - id: "User:1142"
          #     type: "write"
          #     clusterName: "ksql-cluster"
        blueprintEnum: "platinum"
        configOverrides:
          # - min.insync.replicas: 5
          # - test.property: "20"
  scopeFlow:
    # Team based topic name tokenization
    # This tokenization is setup for team : Integration
    # It does not include the team name in the topic name ue to the switch
    # And the topic name tokens are combination of the custom enums and in-place lists
    - shortName: team
      values:
        - "int"
        - "bss"
        - "oss"
      addToTopicName: false
      child:
        blueprintEnum: zones
        addToTopicName: true
        topics:
          name:
            - "test1"
        clients:
          # consumers:
          #   - id: "User:1"
          #     group: "hello"
          producers:
            - id: "User:2"
              group: "hello"
#         child:
#           blueprintEnum: logicalEnv
#           addToTopicName: false
#           clients:
#             consumers:
#               - id: "User:3"
#                 group: "hello"
#             producers:
#               - id: "User:4"
#                 group: "hello"
#           topics:
#             name:
#               - logicalenvtopictest
#             ignoreScope:
#               - dev
#               - pprd
#           child:
#             blueprintEnum: categories
#             addToTopicName: true
#             child:
#               shortName: domain
#               values:
#                 - product
#                 - orders
#                 - shipments
#                 - ~
#               addToTopicName: true
#               clients:
#                 consumers:
#                   - id: "User:5"
#                     group: "hello"
#                 producers:
#                   - id: "User:6"
#                     group: "hello"
#               topics:
#                 name:
#                   - test2
#                   - test3
#                   # - test4
