---
config:
  clusters:
    - name: dev_plaintext
      bootstrapServer: localhost:9092
      clientId: "env::SHEPHERD_DEV_CLIENTID"
      isEnabled: true
    - name: test_ssl
      bootstrapServer: localhost:9093
      isEnabled: false
      clientId: "abhishektest"
      config:
        - security.protocol: SSL
        - ssl.truststore.location: /docker/tls/certs/truststore.jks
        - ssl.keystore.location: /docker/tls/certs/server.keystore.jks
        - ssl.truststore.type: PKCS12
        - ssl.keystore.type: PKCS12
        - ssl.truststore.password: "env::SHEPHERD_TEST_TRUSTSTORE_PASSWORD"
        - ssl.keystore.password: "env::SHEPHERD_TEST_KEYSTORE_PASSWORD"
        - ssl.key.password: "env::SHEPHERD_TEST_KEY_PASSWORD"
    - name: test2_sasl_plaintext
      bootstrapServer: localhost:9093
      isEnabled: false
      clientId: "abhishektest"
      config:
        - security.protocol: SASL_PLAINTEXT
        - sasl.mechanism: PLAIN
        - sasl.jaas.config: 'org.apache.kafka.common.security.plain.PlainLoginModule required username="kafka" password="kafka"'
