---
config:
  clusters:
    - name: dev_plaintext
      bootstrap.server: localhost:9092
      client.id: "abhishektest"
      is.enabled: true
    - name: test_ssl
      bootstrap.server: localhost:9093
      is.enabled: false
      client.id: "abhishektest"
      config:
        - security.protocol: SSL
        - ssl.truststore.location: /docker/tls/certs/truststore.jks
        - ssl.truststore.type: PKCS12
        - ssl.keystore.location: /docker/tls/certs/server.keystore.jks
        - ssl.keystore.type: PKCS12
        - ssl.truststore.password: "password1"
        - ssl.keystore.password: "password1"
        - ssl.key.password: "password1"
      envOverrides:
        - ssl.truststore.password: "SHEPHERD_TEST_TRUSTSTORE_PASSWORD"
        - ssl.keystore.password: "SHEPHERD_TEST_KEYSTORE_PASSWORD"
        - ssl.key.password: "SHEPHERD_TEST_KEY_PASSWORD"
    - name: test2_sasl_plaintext
      bootstrap.server: localhost:9093
      is.enabled: false
      client.id: "abhishektest"
      config:
        - security.protocol: SASL_PLAINTEXT
        - sasl.mechanism: PLAIN
        - sasl.jaas.config: 'org.apache.kafka.common.security.plain.PlainLoginModule required username="kafka" password="kafka"'
      envOverrides:
        - sasl.jaas.config: "SHEPHERD_TEST2_SASL_JAAS_CONFIG"
