---
configs:
  core:
    separatorToken: "."
    deleteUnknownTopics: false
    deleteUnknownACLs: false
  clusters:
    - name: dev_plaintext
      isEnabled: false
      bootstrapServers:
        - localhost:9092
      clientId: "abhishektest1"
    # - name: test_ssl_1WaySSL
    #   isEnabled: false
    #   bootstrapServers:
    #     - localhost:9093
    #   clientId: "abhishektest2"
    #   tlsDetails:
    #     enable2WaySSL: false
    #     trustedCerts:
    #       - "env::SHEPHERD_TRUSTCERT_1_PEM"
    #       - "env::SHEPHERD_TRUSTCERT_2_PEM"
    #     clientCert: "env::SHEPHERD_CLIENTCERT_PEM"
    #     privateKey: "env::SHEPHERD_CLIENTKEY_KEY"
    #     privateKeyPass: "env::SHEPHERD_CLIENTKEY_KEYPASS"
    #   configOverrides:
    #     - security.protocol: SSL
    - name: test2_sasl_plaintext
      isEnabled: false
      bootstrapServers:
        - localhost:9093
      aclType: "kafka_acl"
      clientId: "abhishektest3"
      configOverrides:
        - security.protocol: SASL_PLAINTEXT
        - sasl.mechanism: PLAIN
        - sasl.jaas.config: 'org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="admin-secret"'
    - name: test3_sasl_plaintext_scram
      isEnabled: true
      bootstrapServers:
        - localhost:9093
        - localhost:9094
      aclType: "kafka_acl"
      clientId: "abhishektest4"
      configOverrides:
        - security.protocol: SASL_PLAINTEXT
        - sasl.mechanism: SCRAM-SHA-256
        - sasl.jaas.config: 'org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="admin-pass"'
    - name: test4_confluent_rbac
      isEnabled: false
      bootstrapServers:
        - localhost:9093
      aclType: "confluent_rbac"
      clientId: "abhishektest3"
      configOverrides:
        - cluster.id: "sadfhdskalfhdjkf"
        - mds.url: "https://0.0.0.0:8090"
        - mds.username: "superUser"
        - mds.password: "superUser"
        # - connect.url: "https://0.0.0.0:8083"
        # - schema.registry.url: "https://0.0.0.0:8081"
        # - ksql.cluster.url: "https://0.0.0.0:443"
